FramasVietNam/Controllers/EmptyPageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FramasVietNam.Models.Menu;
using Microsoft.AspNet.Identity;
using FramasVietNam.Common;

namespace FramasVietNam.Controllers
{
    [Authorize]
    public class EmptyPageController : Controller
    {
        ////////////////////////////////////////////////////////////
        //Variable
        #region Variabal
        //important Variable for using get and post data from database
        private MenuManagerEntities db = new MenuManagerEntities();
        //important Variabal cookie in multi language
        private HttpCookie cookie;
        #endregion
        ////////////////////////////////////////////////////////////



        ////////////////////////////////////////////////////////////
        #region empty page
        // GET: EmptyPage
        public ActionResult EmptyPage()
        {
            // CheckCookie and ChangeLanguage always have in action (it will pass data to View)
            CheckCookie();
            ChangeLanguage(cookie.Value);
            // to do something


            //
            return View();
        }
        #endregion
        ////////////////////////////////////////////////////////////



        ////////////////////////////////////////////////////////////
        #region test page
        // GET: EmptyPage
        [HttpGet]
        public ActionResult TestPage()
        {
            // CheckCookie and ChangeLanguage always have in action (it will pass data to View)
            CheckCookie();
            ChangeLanguage(cookie.Value);
            // to do something


            //
            return View();
        }
        // post: EmptyPage
        [HttpPost]
        public ActionResult TestPage(FormCollection fc)
        {

            string str1 = fc["Content"];
            // CheckCookie and ChangeLanguage always have in action (it will pass data to View)
            CheckCookie();
            ChangeLanguage(cookie.Value);
            // to do something
                                   //
            return View();
        }
        //show popup when click detail
        public ActionResult ShowPopup()
        {
            
            var lst_KeyPost = "Hello";
            ViewBag.lst_KeyPost = lst_KeyPost;
            //
            return PartialView("TestPopup");
        }
        #endregion
        ////////////////////////////////////////////////////////////



        ////////////////////////////////////////////////////////////
        //Cookie always exists in controller
        #region Cookie language
        //Check cookie
        public void CheckCookie()
        {
            cookie = Request.Cookies["Language"];
            if (cookie == null || cookie.Value == "")
            {
                Response.Cookies["Language"].Value = "1";
                cookie = Response.Cookies["Language"];
                cookie.Value = "1";
            }
        }

        //get data from entity and push to master view
        public void ChangeLanguage(string textInput)
        {
            Response.Cookies["Language"].Value = textInput;
            object ds_Module = db.sp_Module_Get(mFunction.ToInt(textInput), User.Identity.GetUserName()).OrderBy(m => m.Code).ToList();
            object ds_Group = db.sp_Group_Get(mFunction.ToInt(textInput)).OrderBy(m => m.Code).ToList();
            ViewBag.ds_Module = ds_Module;
            ViewBag.ds_Group = ds_Group;
            string strModuleID = mFunction.ToString(Session["ModuleID"]);
            ViewBag.strModuleID = strModuleID;
            string strGroupID = mFunction.ToString(Session["GroupID"]);
            ViewBag.strGroupID = strGroupID;
        }
        #endregion
        ////////////////////////////////////////////////////////////
    }
}

FramasVietNam/Controllers/FunctionController.cs
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FramasVietNam.Models.Menu;
using Microsoft.AspNet.Identity;
using FramasVietNam.Common;

namespace FramasVietNam.Controllers
{
    [Authorize]
    public class FunctionController : Controller
    {
        ////////////////////////////////////////////////////////////////////////////////
        #region globar variable
        //important Variabal for using get and post data from database
        private MenuManagerEntities db = new MenuManagerEntities();
        //important Variabal cookie in multi language
        private HttpCookie cookie;
        private object ds_Functions;
        #endregion
        ////////////////////////////////////////////////////////////////////////////////



        ////////////////////////////////////////////////////////////////////////////////
        #region Function
        // GET: Function
        [HttpGet]
        public ActionResult Index()
        {
            // CheckCookie and ChangeLanguage always have in action (it pass data to View)
            CheckCookie();
            ChangeLanguage(cookie.Value);
            try
            {
                string moduleID = Session["ModuleID"].ToString();
                string groupID = Session["GroupID"].ToString();
                //passing data to view
                ds_Functions = db.sp_Function_Get(mFunction.ToInt(cookie.Value), mFunction.ToInt(groupID)).ToList();
                ViewBag.ds_Functions = ds_Functions;

                var objMlGrp = db.sp_ModuleGroupGet(mFunction.ToInt(cookie.Value), mFunction.ToInt(moduleID), mFunction.ToInt(groupID)).ToList();
                    var strGroup = "";
                var strModule = "";
                if (objMlGrp != null)
                {
                    strGroup = objMlGrp[0].GroupName;
                    strModule = objMlGrp[0].ModuleName;
                }
                ViewBag.strGroup = strGroup;
                ViewBag.strModule = strModule;
                return View("Index");
            }
            catch (Exception ex)
            {
                string error = ex.ToString();
                ds_Functions = db.sp_Function_Get(mFunction.ToInt(cookie.Value), mFunction.ToInt(0)).ToList();
                ViewBag.ds_Functions = ds_Functions;
                return View("Index");
            }
        }

        // GET: Function
        [HttpPost]
        public ActionResult Index(string ModuleID, string GroupID)
        {
            Session["ModuleID"] = ModuleID;
            Session["GroupID"] = GroupID;
            return RedirectToAction("Index");
        }
        #endregion
        ////////////////////////////////////////////////////////////////////////////////


            
        ////////////////////////////////////////////////////////////////////////////////
        #region Cookie
        //Check cookie
        public void CheckCookie()
        {
            cookie = Request.Cookies["Language"];
            if (cookie == null || cookie.Value == "")
            {
                Response.Cookies["Language"].Value = "1";
                cookie = Response.Cookies["Language"];
                cookie.Value = "1";
            }
        }

        //get data from entity and push to master view
        public void ChangeLanguage(string textInput)
        {
            Response.Cookies["Language"].Value = textInput;
            object ds_Module = db.sp_Module_Get(mFunction.ToInt(textInput), User.Identity.GetUserName()).OrderBy(m => m.Code).ToList();
            object ds_Group = db.sp_Group_Get(mFunction.ToInt(textInput)).OrderBy(m => m.Code).ToList();
            ViewBag.ds_Module = ds_Module;
            ViewBag.ds_Group = ds_Group;
            string strModuleID = mFunction.ToString(Session["ModuleID"]);
            ViewBag.strModuleID = strModuleID;
            string strGroupID = mFunction.ToString(Session["GroupID"]);
            ViewBag.strGroupID = strGroupID;
        }
        #endregion
        ////////////////////////////////////////////////////////////////////////////////
    }
}

FramasVietNam/Views/EmptyPage/EmptyPage.cshtml
@using FramasVietNam.Common
@{
    ViewData["Title"] = "FVN";
    Layout = "~/Views/Shared/_Adminlte.cshtml";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            <a class="fa fa-fw fa-mail-reply" href="@Url.Action("Index","Function")"></a>
            @Language.label("Empty")
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> @Language.label("Function")</a></li>
            <li class="active">@Language.label("Empty")</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row" style="min-height:906px; margin:2px">
            <!-- TO DO List -->
            <div class="box box-primary">
                <div class="box-header">

                    <!-- /.to do something-->
                </div>
                <!-- /.box-header -->
                <div class="box-body">

                    <!-- /.to do something-->
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
    </section>
    <!-- /.content -->
</div>

FramasVietNam/Views/EmptyPage/TestPage.cshtml
@using FramasVietNam.Common
@{
    ViewData["Title"] = "FVN";
    Layout = "~/Views/Shared/_Adminlte.cshtml";
}

@if (ViewBag.Message != null)
{
    <script type="text/javascript" charset="utf-8">
    window.onload = function () {
        alert("@Html.Raw(ViewBag.Message)");
    };
    </script>
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
           
        </h1>
        <ol class="breadcrumb">
            
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row" style="min-height:906px; margin:2px">

            <!-- TO DO List -->
                <div class="box box-primary">

                   @Html.ActionLink("Show", "ShowPopup", "EmptyPage", new { @class = "modal-link btn btn-primary" })

                </div>
            <!-- /.box -->
        </div>
    </section>
    <!-- /.content -->
</div>


@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")

@section Styles{
    <link rel="stylesheet" href="~/Content/adminlte/components/datatables.net-bs/css/dataTables.bootstrap.min.css">
}

@section Scripts{

    <!-- DataTables -->
    <script src="~/Content/adminlte/components/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="~/Content/adminlte/components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>

    <script>
        $(function () {
            $('#example1').DataTable()
        });
    </script>
}

<div id="modal-container" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-content">
    </div>
</div>

<script type="text/javascript">
    $(function () {
        // Initialize numeric spinner input boxes
        //$(".numeric-spinner").spinedit();

        // Initalize modal dialog
        // attach modal-container bootstrap attributes to links with .modal-link class.
        // when a link is clicked with these attributes, bootstrap will display the href content in a modal dialog.
        $('body').on('click', '.modal-link', function (e) {
            e.preventDefault();
            $(this).attr('data-target', '#modal-container');
            $(this).attr('data-toggle', 'modal');
        });

        // Attach listener to .modal-close-btn's so that when the button is pressed the modal dialog disappears
        $('body').on('click', '.modal-close-btn', function () {
            $('#modal-container').modal('hide');
        });

        //clear modal cache, so that new content can be loaded
        $('#modal-container').on('hidden.bs.modal', function () {
            $(this).removeData('bs.modal');
        });

        $('#CancelModal').on('click', function () {
            return false;
        });
    });
</script>

FramasVietNam/Views/EmptyPage/TestPopup.cshtml
@using FramasVietNam.Common
@{
    var lst_KeyPost = mFunction.ToString(ViewBag.lst_KeyPost);
}
<div class="modal-body">

    @using (Html.BeginForm("TestPage", "EmptyPage", FormMethod.Post))
    {
        <div style="overflow-x:auto; background-color:white; padding:20px">
            <button id="btn1" name="btn1">Test onclick submit</button>

            <a id='a' href='#' onClick="a_onClick()"> aaa </a>

            @Html.TextBox("Content", null, new { @class = "form-control", @placeholder = @Language.label("Content") })
            <h1>@lst_KeyPost</h1>
        </div>
    }

</div>

<script type="text/javascript">
    function a_onClick() {
        alert('a_onClick');

        $("#btn1").click();
    }
        //$(function () {
        //    $('#btn2').click(function () {


        //        $("#btn1").click();

        //        debugger;
        //        $('#modal-container').modal('hide');
        //    });
        //});

</script>